config/routes.rb
Rails.application.routes.draw do

  root 'categories#index'

  resources :users
  resources :categories, only: [:index, :new, :create, :show, :destroy] do
    resources :articles, except: :index
  end


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :title, :body, :price, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles

  has_secure_password

  validates :username, :email, presence: true, uniqueness: true
  validates :email, format: { with: /\A\w+@\w+[.]\w+\z/, message: "must be a valid e-mail address" }
  validates :username, :password, length: { minimum: 6, maximum: 18 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionHelper

  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :require_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_category, only: [:new, :create, :edit, :show, :destroy]
  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def new
    @article = Article.new
  end

  def create
    @article = @category.articles.new(article_params)
    if @article.save
      redirect_to action: 'show', id: @article.id
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to action: 'show', id: @article.id
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to category_path(@category)
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :price, :user_id)
  end

  def find_category
    @category = Category.find(params[:category_id])
  end

  def find_article
    @article = Article.find(params[:id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_user, only: [:new, :create, :destroy]
  before_action :find_category, only: [:show, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to '/'
    else
      render 'new'
    end
  end

  def show
    @articles = @category.articles
  end

  def destroy
    @category.destroy
    redirect_to root_path
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def find_category
    @category = Category.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to '/' if logged_in?
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      @user.errors = ["Please enter a valid username/password"]
      render 'new'
    end
  end

  def destroy
    session.clear
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to '/'
    else
      render 'new'
    end
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    true if current_user
  end

  def require_user
    redirect_to '/login' unless logged_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <div>
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being published:</h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for([@category, @article]) do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<%= render "form" %>

app/views/articles/new.html.erb
<%= render "form" %>

app/views/articles/show.html.erb
<h1><%= @category.name %></h1>

<p><%= @article.title %>
<%= @article.body %>
<%= @article.price %></p>

<%= link_to "Edit this Article", edit_category_article_path(@category, @article) %>
<%= link_to 'Delete Article', category_article_path(@category, @article), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/categories/index.html.erb
<h3>Categories</h3>
<ul class="categories">
  <% @categories.each do |categ| %>
    <li><%= link_to "#{categ.name}", category_path(categ) %></li>
  <% end %>
</ul>

<div id="link">
<%= link_to "Make New Category", new_category_path, class: "button black-text" %>
</div>

app/views/categories/new.html.erb
<% if @category.errors.any? %>
  <div>
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
    <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/categories/show.html.erb
<h3><%= @category.name %></h3>

<ul class="categories">
  <% @articles.each do |article| %>
    <li><%= link_to "#{article.title}", category_article_path(@category,article) %></li>
  <% end %>
</ul>

<div class="center">
  <%= link_to 'Add Article', new_category_article_path(@category), class: "button black-text" %>
  <%= link_to 'Delete Category', category_path(@category), method: :delete, data: { confirm: "Are you sure?" }, class: "button black-text" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CraigslistJr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <h1 id="site-logo">Craigslist Jr.</h1>
      <ul class="navigation">
        <li><%= link_to 'Home', root_path %></li>
        <% if logged_in? %>
          <li><%= link_to 'Log Out', logout_path %></li>
          <li><%= link_to "#{ current_user.username }", user_path(current_user) %></li>
        <% else %>
          <li><%= link_to 'Register', new_user_path %></li>
          <li><%= link_to 'Log In', login_path %></li>
        <% end %>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Welcome</h1>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div>
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this registration:</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1>